### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by szemerick** [nasa/CryptoLib#128]

**Comment by szemerick** [comment]
* Unable to run "make gcov" per the wiki. gcov is installed.

**Comment by rjbrown2** [comment]
@szemerick 

Good Catch.  There was a flag added for code coverage.  This was added because it was causing issues with code coverage files being created when we didn't want them to do so.

Use the flag -DCODECOV=1

This will enable the use of the 'make gcov' command.  This has been updated on the wiki.

**Comment by rjbrown2** [comment]
Wiki Updated Complete w/ Cutright.
